Change loggin procedure
etalab/datatools-ui pull request #72
Opened 2017-08-31 16:58 UTC by l-vincent-l

We now only use datagouv oauth, so we don't need the auth0 lock

2017-08-31 17:07 UTC, maukoquiroga commented on lib/common/user/Auth0Manager.js
> +        redirectUri: "http://localhost:9966",
Would that work in prod ?

2017-08-31 17:11 UTC, maukoquiroga commented on lib/common/user/Auth0Manager.js
> +import promisify from 'es6-promisify'
Why ?

2017-08-31 17:12 UTC, bonjourmauko requested changes
Not production ready yet.

2017-08-31 17:12 UTC, maukoquiroga commented on lib/common/user/Auth0Manager.js
> +        redirectUri: "http://localhost:9966",
I don't think that'd work in production.

2017-09-06 08:48 UTC, maukoquiroga commented
@l-vincent-l You tell me when it's ready for another review.

2017-09-07 12:20 UTC, l-vincent-l commented
depends on https://github.com/etalab/transport-datatools-server/pull/16

2017-09-08 14:46 UTC, maukoquiroga commented on lib/common/user/Auth0Manager.js
> +      return !!this.getToken() && this.isTokenExpired();
Why are you using double negation ? For casting ?

2017-09-08 15:06 UTC, bonjourmauko approved these changes

2017-09-08 15:06 UTC, merged